# https://pnpm.io/settings

allowBuilds:
  "@parcel/watcher": true
  core-js: true
  electron-winstaller: true
  esbuild: true
  lightningcss: true
  rolldown: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - quasar@2.21.2
